#!/usr/bin/env bash

folder="$HOME/Notes/"
template="$HOME/.config/nvim/templates/daily_note.md"
terminal=kitty



opennote () { \
    datepath="$(date +%Y/%m/%d_daily.md)"
    name="$(command find "$folder" -type f -printf "%P\n" | grep "$datepath" | head -1)"
    setsid -f $terminal -e nvim $folder$name >/dev/null 2>&1
}

newnote () { \
    datepath="$(date +%Y/%m/)"
    fullpath="$folder$datepath"
    filename="${fullpath}$(date +%d)_daily.md"
    text="# $(date +%F)"

    mkdir -p "$fullpath"

    cp $template $filename
    sed -i "1s/# /$text/" $filename
    setsid -f $terminal -e nvim $filename >/dev/null 2>&1
}

exists () { \
    datepath="$(date +%Y/%m/%d_daily)"
created="$(find "$folder" -type f -printf "%P\n" | grep "$datepath" | head -1)"
if [[ -n "$created" ]]; then
    opennote
else
    newnote
fi
}

exists
