#!/usr/bin/env bash

folder="$HOME/Notes/"
template="$HOME/.config/nvim/templates/daily_note.md"
terminal=kitty



opennote () { \
    date="$(date "+%F")"
name="$(command ls -t1 "$folder" | grep "$date" | head -1)"
    setsid -f $terminal -e nvim $folder$name".md" >/dev/null 2>&1
}

newnote () { \
    name="$(date +%F_%T | tr ':' '-')"
    text="# $(date "+%F")"
    cp $template $folder$name".md" && sed -i "1s/# /$text/" $folder$name".md" && setsid -f $terminal -e nvim $folder$name".md" >/dev/null 2>&1
}

exists () { \
    date="$(date "+%F")"
created="$(command ls -t1 "$folder" | grep "$date" | head -1)"
if [[ -n "$created" ]]; then
    opennote
else
    newnote
fi
}

exists
