#!/usr/bin/env bash
# shamelessly copied from https://github.com/BreadOnPenguins/scripts/blob/master/dmenu_notes

folder="$HOME/Notes/"
terminal=kitty


newnote () { \
    name="$(echo "" | dmenu -c -sb "#9ece6a" -p "Enter a name: " <&- | tr ' ' '-' | awk '{print tolower($0)}' )" || exit 0
    : "${name:=$(date +%F_%T | tr ':' '-')}"
    setsid -f $terminal -e nvim $folder$name".md" >/dev/null 2>&1 && notify-send "New note created"
}

selected () { \
    choice=$(echo -e "New\n$(command ls -t1 $folder)" | dmenu -c -l 5 -i -p "Choose note or create new: ")
case $choice in
    New) newnote ;;
    *.md) setsid -f "$TERMINAL" -e nvim "$folder$choice" >/dev/null 2>&1 ;;
    *) exit ;;
esac
}

selected
