#!/usr/bin/env bash
# shamelessly copied from https://github.com/BreadOnPenguins/scripts/blob/master/dmenu_notes

folder="$HOME/Notes/"
terminal=kitty

# TODO: newnote in parent folder based on date, acc to old format


newnote () { \
    ext="$1"
    name="$(echo "" | dmenu -c -sb "#9ece6a" -p "Enter a name: " <&- | tr ' ' '_' | awk '{print tolower($0)}' )"
    [ -z "$name" ] && exit 0

    datepath=$(date +%Y/%m/)
    fullpath="$folder$datepath"
    filename="$(date +%d)_${name}.${ext}"
    mkdir -p "$fullpath"

    setsid -f $terminal -e nvim "$fullpath/$filename" >/dev/null 2>&1 && notify-send "New note created"
    wait
    if [ $ext = "typ" && ]; then
        typst watch "$fullpath/$filename" >/dev/null 2>&1
    fi
}

bare () { \
    name="$(echo "" | dmenu -c -sb "#9ece6a" -p "Enter a name: " <&- | tr ' ' '_' | awk '{print tolower($0)}' )" || exit 0
    [ -z "$name" ] && exit 0
    setsid -f $terminal -e nvim $folder$name".md" >/dev/null 2>&1
}

ext () { \
    ext=$(echo -e "Bare\nmd\ntyp" | dmenu -c -l 3 -i -p "Choose file type: " )
    [ -z "$ext" ] && exit 0
case $ext in
    Bare) bare ;;
    *) newnote "$ext";;
esac
}

selected () { \
    choice=$(echo -e "New\n$(command find "$folder" -type f -printf "%T@ %P\n" | grep -E "\.(md|typ)$" | sort -nr | cut -d' ' -f2-)" | dmenu -c -l 5 -i -p "Choose note or create new: ")
case $choice in
    New) ext ;;
    *.md|*.typ) setsid -f $terminal -e nvim "$folder$choice" >/dev/null 2>&1 ;;
    *) exit ;;
esac
}

selected
