#!/usr/bin/env bash
# shamelessly copied from https://github.com/BreadOnPenguins/scripts/blob/master/dmenu_sys

folder="$HOME/"
scripts_folder="$HOME/.scripts"
terminal=kitty

case "$(printf "kill\nzzz\nreboot\nshutdown\ntimer" | dmenu -i -c -l 5)" in
	kill) ps -u $USER -o pid,comm,%cpu,%mem | dmenu -i -c -l 10 -p Kill: | awk '{print $1}' | xargs -r kill ;;
	zzz) systemctl suspend-then-hibernate -i ;;
	reboot) systemctl reboot -i ;;
	shutdown) systemctl poweroff -i ;;
    timer) source "$scripts_folder/dmenu_kill_timer" ;;
	*) exit 1 ;;
esac

