#!/usr/bin/env bash

folder="$HOME/"
terminal=kitty

on () { \
    conn="$1"
    sudo -A nmcli con modify $conn ipv4.ignore-auto-dns no
    sudo -A nmcli g reload dns-rc
    sudo -A systemctl restart NetworkManager
    notify-send "DNS switched on"
}

off () { \
    conn="$1"
    sudo -A nmcli con modify $conn ipv4.ignore-auto-dns yes
    sudo -A nmcli g reload dns-rc
    sudo -A systemctl restart NetworkManager
    notify-send "DNS switched off"
}

switch () { \
    conn=$(nmcli connection show | head -n 2 | tail -n 1 | awk '{print $1;}')
    choice=$(echo -e "ON\nOFF" | dmenu -c -l 2 -i -p "DNS Switch: ")
    choice_awk=$(echo $choice | awk '{print tolower($0);}')
case $choice_awk in
    on) on $conn ;;
    off) off $conn ;;
    *) notify-send "DNS switch canceled" && exit ;;
esac
}

switch
