#!/usr/bin/env bash
# shamelessly copied from https://github.com/BreadOnPenguins/scripts/blob/master/dmenu_notes

folder="$HOME/Notes/"
terminal=kitty


newnote () { \
    ext="$1"
    name="$(echo "" | dmenu -c -sb "#9ece6a" -p "Enter a name: " <&- | tr ' ' '-' | awk '{print tolower($0)}' )" || exit 0
    [ -z "$name" ] && exit 0

    datepath=$(date +%Y/%m/)
    fullpath="$folder$datepath"
    filename="$(date +%d)_${name}.${ext}"
    mkdir -p "$fullpath"

    setsid -f $terminal -e nvim "$fullpath/$filename" >/dev/null 2>&1 && notify-send "New note created"
}

ext () { \
    ext=$(echo -e "md\ntyp" | dmenu -c -l 2 -i -p "Choose file type: " )
    [ -z "$ext" ] && exit 0
    newnote "$ext"
}

selected () { \
    choice=$(echo -e "New\n$(command find "$folder" -type f -printf "%T@ %P\n" | grep -E "\.(md|typ)$" | sort -nr | cut -d' ' -f2-)" | dmenu -c -l 5 -i -p "Choose note or create new: ")
case $choice in
    New) ext ;;
    *.md|*.typ) setsid -f $terminal -e nvim "$folder$choice" >/dev/null 2>&1 ;;
    *) exit ;;
esac
}

selected
