#!/usr/bin/env bash

seconds="$1"

folder="$HOME/.local/share/sounds"
sound_file="$folder/timer-alert.ogg"

sleep "$seconds" \
    && notify-send "Timer ended" "It is now $(date +%R)" -u "CRITICAL" \
    && paplay "$sound_file"
