#!/usr/bin/env bash

scripts_folder="$HOME/.scripts/fuzzel"

case "$(printf "kill\nzzz\nreboot\nshutdown\ntimer" | fuzzel --dmenu -l 5)" in
    kill) ps -u $USER -o pid,comm,%cpu,%mem | fuzzel --dmenu -l 10 -p Kill: | awk '{print $1}' | xargs -r kill ;;
    zzz) systemctl suspend-then-hibernate -i ;;
    reboot) systemctl reboot -i ;;
    shutdown) systemctl poweroff -i ;;
    timer) source "$scripts_folder/fuzzel_kill_timer" ;;
    *) exit 1 ;;
esac


